# Import and get the version

In [2]:
import torch
torch.__version__

'2.5.1'

# Create an scalar


In [8]:
def print_scalar_info(scalar):
    """
    Print detailed information about the given scalar tensor.

    Parameters:
      scalar (torch.Tensor): A tensor containing a single scalar value.
    """
    print(f"Scalar:\n{scalar}\n")
    print(f"Scalar type:\n{type(scalar)}\n")
    print(f"Scalar dimension:\n{scalar.ndim}\n")
    
    # Get the Python number within the tensor (only works with one-element tensors)
    item = scalar.item()
    print(f"Scalar item:\n{item}\n")

scalar = torch.tensor(7)
print_scalar_info(scalar)






Scalar:
7

Scalar type:
<class 'torch.Tensor'>

Scalar dimension:
0

Scalar item:
7



# Create a vector, matrix and tensor

In [18]:
def print_tensor_info(tensor):
    """
    Print detailed information about the given tensor of at least 2 elements.

    Parameters:
      Tensor (torch.Tensor): A tensor containing a single scalar value.
    """
    print(f"Tensor:\n{tensor}\n")
    print(f"Tensor type:\n{type(tensor)}\n")
    print(f"Tensor dimension:\n{tensor.ndim}\n")
    print(f"Tensor shape:\n{tensor.shape}\n")
    

vector = torch.tensor([7, 7])
print_tensor_info(vector)

Tensor:
tensor([7, 7])

Tensor type:
<class 'torch.Tensor'>

Tensor dimension:
1

Tensor shape:
torch.Size([2])



In [19]:
matrix = torch.tensor([[7, 8],[9, 10]])
print_tensor_info(matrix)

Tensor:
tensor([[ 7,  8],
        [ 9, 10]])

Tensor type:
<class 'torch.Tensor'>

Tensor dimension:
2

Tensor shape:
torch.Size([2, 2])



In [20]:
tensor_3d = torch.tensor([[[1, 2], [3, 4]]])
print_tensor_info(tensor_3d)

Tensor:
tensor([[[1, 2],
         [3, 4]]])

Tensor type:
<class 'torch.Tensor'>

Tensor dimension:
3

Tensor shape:
torch.Size([1, 2, 2])



# Create a random tensor

In [21]:
random_tensor = torch.rand(size=(3, 4))
random_tensor


tensor([[0.0908, 0.5245, 0.1840, 0.2426],
        [0.8294, 0.7028, 0.4865, 0.5038],
        [0.4769, 0.7804, 0.0543, 0.4440]])